name: plb
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy=1.21.1
  - torchvision
  - cudatoolkit=10.2
  - pip:
    - joblib
    - gym==0.14.0
    - moviepy
    - opencv-python
    - matplotlib
    - transforms3d
    - python-dateutil
    - cloudpickle
    - pyyaml
    - yacs
    - sklearn
    - taichi==0.7.26
    - pyquaternion
    - transformations
